### ISSUE TITLE
Pointer events not firing when bundled with Parcel bundler

### ISSUE THREAD

**Issue by danmarshall** [uber-web/mjolnir.js#30]
Hello,
Sorry if this is not the right place to file this bug, but it appears it might be related to #13 ?

## Setup
Install the [Parcel bundler](https://parceljs.org/)
`npm install -g parcel`

## Repro case
1. Clone `deck.gl`
2. Navigate to `deck.gl/examples/website/plot/`
3. Move this line of code from `index.html` to `app.js`: 
```
App.renderToDOM(document.getElementById('app'));
```
4. `parcel serve ./index.html --open`

### Expected
Mouse / pointer events to orbit the view

### Actual
View does not respond to mouse

**Comment by Pessimistress** [comment]
Can you try the example on deck.gl's 6.3-release branch?

**Comment by danmarshall** [comment]
Hmmm I guess not - found some Parcel documentation that says it should: https://parceljs.org/module_resolution.html#package.json-%60browser%60-field

**Comment by danmarshall** [comment]
... but it sounds like it only works as an alias for `main`. Example:
```
{
  "main": "build/d3.Node.js",
  "browser": "build/d3.js",
  "module": "index"
}
```
It does not appear to work with the current:
```
  "browser": {
    "./dist/cjs/utils/hammer.js": "./dist/cjs/utils/hammer.browser.js",
    "./dist/esm/utils/hammer.js": "./dist/esm/utils/hammer.browser.js"
  }
```

**Comment by Pessimistress** [comment]
Looks like it should? https://github.com/parcel-bundler/parcel/issues/200

Can you inspect your bundle and see if hammer.js is included?

**Comment by danmarshall** [comment]
hammer.js was included. I will try to see if [browser-resolve](https://github.com/defunctzombie/node-browser-resolve) is finding it correctly. BTW it does say it should support the way you are doing it: 
https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced

**Comment by danmarshall** [comment]
hmmm, perhaps it is a Windows thing? https://github.com/parcel-bundler/parcel/issues/1883#issuecomment-441110385

**Comment by danmarshall** [comment]
Hi @Pessimistress I have set up a simple repo to demonstrate this bug:
https://github.com/danmarshall/parcel-browser-field

I can close this issue if you aren't able to reproduce, it would then be a bug in Parcel.
Thank you for your patience! 👍

**Comment by Pessimistress** [comment]
Thanks for following up on this. Could you post an update here when it's resolved? I don't have a PC so it's been a little difficult for me to track compatibility on Windows.

**Comment by danmarshall** [comment]
Yes I will follow up here. Meanwhile, can you try to repro on your Mac?

**Comment by danmarshall** [comment]
Ok, bug does not repro on a Mac. Not your bug, sorry and thanks!

**Comment by danmarshall** [comment]
Bug happens when the files are in subfolders - backslashes on windows do not match forward slashes in a path. I've sent a [PR to Parcel](https://github.com/parcel-bundler/parcel/pull/2445).
