### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by supersonicclay** [uber-web/mjolnir.js#33]
Repro:
Click any of the links on the left of this page: https://uber-web.github.io/mjolnir.js/#/documentation/overview
Click GitHub link

Result:
Broken links

**Comment by ibgreen** [comment]
@supersonicclay 	Thanks for reporting. This seems to be the case of most of the ocular based framework. math.gl, probe.gl, etc are all broken in this regard.

@jckr: we need to get the micro frameworks onto ocular-gatsby asap.

@Pessimistress 	@jianhuang01 We need to reinforce our release process to ensure we catch this. The links in these sites have probably been broken for months, making our docs more or less unusable.
