### ISSUE TITLE
mjolnir.js breaks gatsby build

### ISSUE THREAD

**Issue by ibgreen** [uber-web/mjolnir.js#39]
Apparently `navigator` is defined but `navigator.userAgent` is not during gatsby build.

<img width="720" alt="Screen Shot 2019-06-07 at 3 09 49 PM" src="https://user-images.githubusercontent.com/7025232/59136079-60654680-8936-11e9-8406-519b12953990.png">

**Comment by ibgreen** [comment]
@georgios-uber

**Comment by georgios-uber** [comment]
Change that line to:
`export var userAgent = (typeof navigator !== 'undefined' && navigator.userAgent) ? navigator.userAgent.toLowerCase() : '';`
