### ISSUE TITLE
Possibility to mark event listeners as passive?

### ISSUE THREAD

**Issue by ibgreen** [uber-web/mjolnir.js#6]
We get a lot of console warnings about non-passive event handling. Maybe add an option to `EventManager` class to register event handlers as passive?

https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive

![Uploading Screen Shot 2017-10-15 at 5.48.58 PM.png…]()

**Comment by 7iomka** [comment]
any ideas?

**Comment by jaydenseric** [comment]
This causes a lot of console warnings with [`react-map-gl`](https://github.com/uber/react-map-gl):

<img width="665" alt="screen shot 2019-01-08 at 6 58 00 pm" src="https://user-images.githubusercontent.com/1754873/50817252-57684d00-1377-11e9-9017-bd64d8959952.png">

**Comment by Pessimistress** [comment]
We cannot register scroll events to be passive - it will break `preventDefault` which react-map-gl needs for scroll zoom.

According to [this](https://developers.google.com/web/updates/2016/06/passive-event-listeners) passing `{ passive: false }` to `addEventListener` will remove the violation warning. We will need a [polyfill](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) for older browsers.

**Comment by Pessimistress** [comment]
2.0.3
