### ISSUE TITLE
Up & down swipe mobile navigation problem after swipe event register

### ISSUE THREAD

**Issue by mzalevski** [uber-web/mjolnir.js#72]
eventManager = new EventManager(document.getElementById("container"));

    eventManager.on({
      swipeleft: () => console.log("left"),
      swiperight: () => console.log("right"),
    });

After I registered swipeleft & swiperight handlers, the up & down swipe navigation on mobile does not work on that container.

I am using Svelte & Sapper. Android OS + Chrome browser.

**Comment by Pessimistress** [comment]
You may want to try set the [touchAction](https://uber-web.github.io/mjolnir.js/docs/api-reference/event-manager#constructor-1) option.

**Comment by mzalevski** [comment]
@Pessimistress it helped! Thanks a lot :)

    eventManager = new EventManager(document.getElementById("swipeable"), {
      touchAction: "pan-y",
    });
