### ISSUE TITLE
Wheel event.delta intermittently NaN in Firefox

### ISSUE THREAD

**Issue by neftaly** [uber-web/mjolnir.js#74]
`event.delta` is `NaN` in roughly 1/3 to 1/20 of wheel events on Firefox (tested FF v85 Linux).

https://codesandbox.io/s/modest-platform-uue38?file=/src/index.js
```js
import { EventManager } from "mjolnir.js";

const app = document.getElementById("app");
app.innerHTML = "<h1>scrollwheel test</h1>";

const eventManager = new EventManager();
eventManager.setElement(app);
eventManager.on({
  wheel: ({ delta }) => {
    app.innerHTML += `<div>${delta}</div>`;
  }
});
```

**Comment by Pessimistress** [comment]
Looks like the missing delta is coming from these legacy events: https://github.com/uber-web/mjolnir.js/blob/a9c31248921cbd09e9c908379c5927ec5e30d32d/src/constants.js#L80-L83

I think we can safely subscribe to just the `wheel` event now: https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event#browser_compatibility
